### ISSUE TITLE
Fix the incorrect branch name in the installation instructions in README.md

### ISSUE THREAD

**Issue by ilyamt-tandemg** [sebthom/more-clink-completions#3]
This command results in error as the branch is called **v2-releases** and not **v2-release**:
> git clone https://github.com/sebthom/more-clink-completions --branch v2-release --single-branch [REPO_PATH]

Hence, the correct command should be:
git clone https://github.com/sebthom/more-clink-completions --branch v2-releases --single-branch [REPO_PATH]

**Comment by sebthom** [comment]
Thanks!
