### ISSUE TITLE
Error more-clink-completions.lua:6: attempt to call field 'getargmatcher' (a nil value)

### ISSUE THREAD

**Issue by lukashevich-t** [sebthom/more-clink-completions#4]
I have clink  v1.2.41.647c1b installed.
Installed more-clink-completions:

> `git clone https://github.com/sebthom/more-clink-completions --branch v2-releases --single-branch  d:\utils\clink\completions\more-clink-completions`

and got message:

> `Script path 'd:\utils\clink\completions\more-clink-completions' installed.
> 
> ...etions\more-clink-completions\more-clink-completions.lua:6: attempt to call field 'getargmatcher' (a nil value)
> stack traceback:
>         ...etions\more-clink-completions\more-clink-completions.lua:6: in function 'register'
>         ...etions\more-clink-completions\more-clink-completions.lua:6: in function 'main'
>         ...etions\more-clink-completions\more-clink-completions.lua:6: in function <...etions\more-clink-completions\more-clink-completions.lua:6>
>         [C]: in function 'xpcall'
>         ...etions\more-clink-completions\more-clink-completions.lua:6: in function '__luapack_entry__'
>         ...etions\more-clink-completions\more-clink-completions.lua:6: in main chunk`

This message arises each time I start cmd.exe.
Completions isn't working.
I don't have any other clink scripts installed.

My OS is Windows x64 v10.0.19045 build 19045.
If you need more info about my PC/OS, please let me know.

**Comment by lukashevich-t** [comment]
My OS is Windows x64 v10.0.19045 build 19045

**Comment by sebthom** [comment]
clink v1.2.41.647c1b seems to be a very old clink version. Please try to upgrade to a recent release. I am running [1.4.27.733e84](https://github.com/chrisant996/clink/releases/tag/v1.4.27)

The missing `getargmatcher` was introduced in v1.3.12 https://github.com/chrisant996/clink/blob/745b0bd7bc1509a698aad8726a7edb7771f128db/CHANGES?plain=1#L492-L505

**Comment by lukashevich-t** [comment]
Well, my clink version was too old. With latest version of clink, completions works fine.
