### ISSUE TITLE
[Request] Arduino CLI

### ISSUE THREAD

**Issue by DRSDavidSoft** [sebthom/more-clink-completions#6]
Hi there, I just found this awesome project, impressive to see these new completions! 👍🏻 

I was wondering if I could ask for a new completion, for the `arduino-cli` project. I originally asked for this in https://github.com/vladimir-kotikov/clink-completions/issues/177, but I'm not very proficient in lua in order to contribute solid code myself, and as Chris doesn't use them, he was unable to help in this regard.

These tools are very useful for embedded development, and I'm interested to have a go with Haxe, to see if I could contribute some code for this.

If possible, I would appreciate it if you could consider adding this to `more-clink-completions`, even a starting point, so that I could contribute and add more to it.

**Comment by sebthom** [comment]
You can have a look at the exising commands under https://github.com/sebthom/more-clink-completions/tree/v2/src/more_clink_completions/completions Since Haxe is type-safe implementing new commands is pretty straight forward.

```haxe
class ArduinoCli {

   static final COMMANDS = [
     "board",
     "burn-bootload",
      // ... more commands
   ]

   public static function register() {
      Clink.argMatcher("arduino-cli").setDelayedInitializer(registerNow);
   }

   static function registerNow(parser:ArgMatcher, commandWord:String) {
      parser.addFlags([
         "-h", "--help",
         "-v", "--verbose",
         // ... more flags
      ])
         .addArg(COMMANDS)
         .noFiles();
   }
}
```
